stages:
  - build
  - lint

eslint:
  image: node
  tags:
    - docker
  stage: lint
  script:
    - npm install -g lerna
    - lerna bootstrap --hoist
    - npm run lint
build_server:
  image: mcr.microsoft.com/dotnet/sdk:5.0
  tags:
    - docker
  stage: build
  script:
    - dotnet build
