stages:
  - build
  - test
  - lint

eslint:
  image: node
  tags:
    - docker
  stage: lint
  script:
    - npm install -g lerna
    - lerna bootstrap --hoist
    - npm run lint
build:
  image: mcr.microsoft.com/dotnet/sdk:5.0
  tags:
    - docker
  stage: build
  script:
    - cd server
    - dotnet build -c Release
test:
  image: mcr.microsoft.com/dotnet/sdk:5.0
  tags:
    - docker
  stage: test
  script:
    - cd server
    - dotnet test -c Release
